services:
  - type: web
    name: easypark-backend
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:mysql://bfbh4n2ccukyxuo2sny4-mysql.services.clever-cloud.com:3306/bfbh4n2ccukyxuo2sny4?useSSL=true&requireSSL=true&serverTimezone=UTC
      - key: DATABASE_USERNAME
        value: uzk5dknvpy7byyoo
      - key: DATABASE_PASSWORD
        value: w7HGO2zBZN2qm2HEdV2s
      - key: JWT_SECRET
        generateValue: true
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    healthCheckPath: /actuator/health
    autoDeploy: true

